name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: |
           cd ./CV 
           dotnet restore
    - name: Build
      run: |
           cd ./CV
           dotnet build --no-restore
    - name: Test
      run: |
           cd ./CV
           dotnet test --no-build --verbosity normal
